version: 2
updates:
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: weekly
    groups:
      golang-dependencies:
        patterns:
          - "*"
    reviewers:
      - "mendersoftware/qa-dependabot-reviewers"
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: docker
    schedule:
      interval: weekly
    reviewers:
      - "mendersoftware/qa-dependabot-reviewers"
